name: CI

on:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6

      - uses: pnpm/action-setup@0ebf47130e4866e96fce0953f49152a61190b271 # v6

      - uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6
        with:
          node-version-file: '.nvmrc'

      - name: Install dependencies
        run: pnpm install

      - name: Build
        run: |
          pnpm slidev build slides-en.md --without-notes --base /${{ github.event.repository.name }}/en/ --out dist/en
          pnpm slidev build slides-fr.md --without-notes --base /${{ github.event.repository.name }}/fr/ --out dist/fr
